export const colorMask =
	'data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%2024%2024%22%3E%3Ccircle%20cx=%2212%22%20cy=%2212%22%20r=%2210%22%20fill=%22black%22/%3E%3C/svg%3E'

export const paneExpandableIcon = 'material-symbols:tune'

// Visible component modules are alphabetical. Provider-owned surfaces that do
// not render their own inline demo are grouped at the end instead of creating
// an empty first section.
export const gallerySectionOrder = [
	'App',
	'Balloon',
	'BindIcon',
	'ColorIcon',
	'GlslCanvas',
	'Icon',
	'IconIndicator',
	'InputAngle',
	'InputButton',
	'InputButtonToggle',
	'InputCheckbox',
	'InputCode',
	'InputColor',
	'InputComplex',
	'InputCubicBezier',
	'InputDropdown',
	'InputDrum',
	'InputGroup',
	'InputNumber',
	'InputPosition',
	'InputRadio',
	'InputRotary',
	'InputShuffle',
	'InputSize',
	'InputString',
	'InputSwitch',
	'InputTextBase',
	'InputTime',
	'InputTranslate',
	'InputVec',
	'Markdown',
	'Menu',
	'MonacoEditor',
	'MultiSelectPopup',
	'PaneExpandable',
	'PaneFloating',
	'PaneModal',
	'PaneModalComplex',
	'PaneModalTabs',
	'PaneSplit',
	'PaneZUI',
	'ParameterGrid',
	'Popover',
	'Ruler',
	'SvgIcon',
	'Tabs',
	'Timeline',
	'TitleBar',
	'Tooltip',
	'TweakOverlay',
	'Viewport',
	'CommandPalette',
	'TweeqProvider',
] as const
