import {assetPath} from '../assetPath'
import {Heading} from './docs'

export function FeaturesPage() { return <div {...{'vp-content': ''}} data-testid="features-page">
	<Heading level={1} id="features">Features</Heading><Heading level={2} id="specialized-inputs-for-creative-software">Specialized Inputs for Creative Software</Heading><img src={assetPath('assets/components_list.webp')} alt="" /><p>Tweeq offers a suite of specialized input components tailored for professional creative applications. Beyond standard color pickers and numeric sliders, it includes rotary knobs, two-dimensional offset controls, and even timecode-specific interfaces. These components are designed to meet the nuanced needs of graphic design, digital audio workstations (DAWs), and video editing tools, providing precise and efficient parameter manipulation.</p>
	<Heading level={2} id="drag-to-tweak-interaction">“Drag-to-tweak” Interaction</Heading><p>Several input components within Tweeq support the “drag-to-tweak” interaction paradigm, allowing users to adjust values by dragging over pads, handles, and similar elements.</p><p>During a drag operation, you can modify the parameter being adjusted, change the adjustment scale, or constrain the adjustment to a specific axis by pressing designated keys.</p><p>While specific key functions may vary across components, the general semantics are as follows:</p><ul><li><code>Shift</code>: Increases the adjustment scale, enabling quicker value changes.</li><li><code>Alt</code> (<code>Option</code> on Mac): Decreases the adjustment scale, allowing for finer, more precise adjustments.</li><li><code>Q</code>: Activates value snapping, aligning adjustments to predefined increments for consistency.</li><li><code>A</code> / <code>R</code>: Activates absolute/relative mode.</li></ul><p>Consistently, dragging to the right or upward increases parameter values. However, for parameters with geometric counterparts in the viewport, such as position or rotation, the drag direction aligns with the corresponding geometric interpretation (e.g., dragging downward increases the Y-axis value in <a href="#/components#inputposition">InputPosition</a>).</p>
	<Heading level={2} id="simultaneous-editing">Simultaneous Editing</Heading><p>Many components in Tweeq support simultaneous selection and editing, akin to the behavior of spreadsheet cells. By holding down the <code>Shift</code> or Meta key (<code>Ctrl</code> on Windows, <code>Command</code> on Mac), users can select multiple components and adjust them concurrently, streamlining workflows that require coordinated parameter changes across multiple elements.</p>
	<Heading level={2} id="expression-support">Expression Support</Heading><p>Tweeq supports dynamic parameter control through JavaScript expressions. Users can input any valid JavaScript expression to define parameter values.</p><p>Expressions can reference several predefined variables:</p><ul><li><code>x</code>: Current value of the parameter</li><li><code>i</code>: Zero-based index of the current parameter.</li></ul>
</div> }
